[project]
	authors = [{ name = "An-E IOSI", email = "bazikdev@protonmail.com" }]
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"Intended Audience :: Developers",
		"Natural Language :: English",
		"Operating System :: Windows",
		"Programming Language :: C",
		"Programming Language :: Python :: 3 :: Only",
		"Programming Language :: Python :: 3",
		"Programming Language :: Python :: 3.14",
		"Programming Language :: Python :: Free Threading :: 2 - Beta",
		"Programming Language :: Python",
		"Topic :: Software Development :: Build Tools",
		"Topic :: Software Development :: Libraries :: Python Modules",
		"Topic :: System :: Software Distribution",
		"Topic :: Utilities",
	]
	description = "Read and write Microsoft Installer files"
	keywords = ["msilib"]
	license = "PSF-2.0"
	license-files = ["LICENSE"]
	name = "py-msilib"
	readme = "README.md"
	requires-python = ">=3.14"
	version = "0.1.0"

	[project.urls]
		Changelog     = "https://github.com/aneiosi/py-msilib/releases"
		Documentation = "https://docs.python.org/3.12/library/msilib.html"
		Source        = "https://github.com/aneiosi/py-msilib"

[build-system]
	build-backend = "hatchling.build"
	requires      = ["hatchling"]

[tool.coverage]
	[tool.coverage.html]
		directory = "build/coverage_html_report"

	[tool.coverage.paths]
		source = ["*/msilib/", "src/msilib/"]

	[tool.coverage.report]
		# Regexes for lines to exclude from consideration
		exclude_also = [
			"@(abc\\.)?abstractmethod", # Don't complain about abstract methods, they aren't run
			"def __repr__",             # Don't complain about missing debug-only code
			"if TYPE_CHECKING:",        # TYPE_CHECKING block is never executed during pytest run
		]
		ignore_errors = true
		precision = 2

	[tool.coverage.run]
		command_line    = "-m pytest"
		dynamic_context = "test_function"
		parallel        = true
		relative_files  = true
		source          = ["msilib"]

[tool.hatch.build.targets.wheel]
	packages = ["src/msilib"]

[tool.pixi]
	[tool.pixi.workspace]
		channels  = ["conda-forge"]
		platforms = ["win-64"]

	[tool.pixi.pypi-dependencies]
		py-msilib = { path = ".", editable = true }

	[tool.pixi.dependencies]
		python = ">=3.14"

	[tool.pixi.feature.dev.dependencies]
		coverage  = ">=7.13.5,<8"
		hatchling = ">=1.29.0,<2"
		pytest    = ">=9.0.2,<10"
		ruff      = ">=0.15.7,<0.16"
		ty        = ">=0.0.24,<0.0.25"

	[tool.pixi.environments]
		default = { solve-group = "default" }
		dev     = { features = ["dev"], solve-group = "default" }

	[tool.pixi.tasks]
		fmt       = "ruff format src tests"
		fmt-check = "ruff format --check src tests"
		lint      = "ruff check src tests"
		lint-fix  = "ruff check --fix src tests"
		typecheck = "ty check src"

		coverage = "coverage run"
		test = "pytest tests -v"
		test-cov = { cmd = "coverage run && coverage combine && coverage html", depends-on = [
			"coverage",
		] }

		build-all   = "python -m build --outdir dist"
		build-check = "twine check dist/*"
		build-sdist = "python -m build --sdist --outdir dist"
		build-wheel = "python -m build --wheel --outdir dist"

		clean = { cmd = """
		python -c "
		import shutil
		from pathlib import Path
		for p in ['build', 'dist', 'wheelhouse', '.coverage*', '*.egg-info', '__pycache__', '.pytest_cache', '.ruff_cache']:
				for path in Path('.').rglob(p):
						if path.is_dir():
								shutil.rmtree(path, ignore_errors=True)
						elif path.is_file():
								path.unlink(missing_ok=True)
		"
		""" }

		ci         = { depends-on = ["lint", "test-cov", "typecheck"] }
		dev-check  = { depends-on = ["fmt-check", "lint", "typecheck"] }
		pre-commit = { depends-on = ["fmt", "lint-fix", "test", "typecheck"] }
		release    = { depends-on = ["build-all", "build-check", "clean"] }

[tool.pytest]
	addopts = ["--strict-markers", "-rpfEsXx"]
	filterwarnings = [
		"ignore::DeprecationWarning:distutils.*",
		"ignore::DeprecationWarning:pkg_resources.*",
		"ignore::DeprecationWarning:setuptools.*",
	]
	minversion = "9.0"
	testpaths = ["tests"]

[tool.ruff]
	exclude        = [".pixi", ".venv"]
	line-length    = 99
	lint           = { preview = true }
	target-version = "py314"

[tool.setuptools]
	include-package-data = true
	package-dir          = { "" = "src" }
	zip-safe             = false

	[tool.setuptools.packages.find]
		namespaces = false
		where      = ["src"]

	[[tool.setuptools.ext-modules]]
		depends   = ["src/msilib/include/_msi.h", "src/msilib/include/pythoncapi_compat.h"]
		libraries = ["cabinet", "msi", "rpcrt4"]
		name      = "msilib._msi"
		sources   = ["src/msilib/_msi.c"]
